---
title: "3.1) Errors and messages"
author: "Hugo Flávio"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{3.1) Errors and messages}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Index

1. [Preparing your data](1.0.workspace_requirements.html)
    1. [Structuring the study area](1.1.study_area.html)
1. [Running actel](2.0.running_analysis.html)
    <!-- 1. [Installing a TeX distribution](2.1.installing_tex.html) -->
1. [What is actel doing?](3.0.the_sorting_process.html)
    1. [**Errors and messages**](3.1.messages.html)
1. [Inspecting the results](4.inspecting_results.html)
1. [Refining the results](5.refining_results.html)

## List of Messages, Warnings and Errors

In this page you can find additional help if you run into trouble using actel. Each message/warning/error in this page is followed by a short text detailing the problem. If your problem persists after trying out the proposed solutions, feel free to contact the development team.

### Errors and messages while importing the data:

1. **The target path does not exist**

	```
	Error: The selected path does not exist. Details:
	  Current directory: [...]
	  Path: [...]
	You may either:
	  a) continue the analysis in the current directory;
	  b) restart the function."
	Decision:(a/b) 
	```

	It would appear that you asked actel to move to a folder that does not exist. Revise the `path` variable and make sure you typed the path correctly. If the problem persists, try moving to the target directory before hand (e.g. with `setwd()`) and running actel without setting a `path`.

1. **Report exceptions**

	```
	W: 'Report' option can only be activated if 'ggplot2' and 'reshape2' are installed. Please install these. Deactivating 'Report' for the current job.
	```

	Actel could not access libraries ggplot2 and reshape2. Install these so actel can draw graphics.

	```
	W: 'Report' directory already present. Overwriting files already present.
	W: 'Report' directory already present. Skipping files already present.
	```

	If you are running actel for the second time in a given folder, the 'Report' directory may have already been created. Depending on whether you set `redraw`as TRUE or FALSE, previously present files may get overwritten.

1. **Some files are missing**

	```
	Error: Could not find a 'spatial.csv' file in the working directory.
	Error: Could not find a 'biometrics.csv' file in the working directory.
	Error: Could not find a 'detections' folder nor a 'detections.csv' file.
	```

	Actel could not find one of the needed files in the working directory. Please make sure that you are targetting the correct directory, and that the files are named exactly as described.

1. **Something is wrong in the input files**

	```
	Error: No 'Array' column found in the spatial file, but a 'Group' column is present. Use the 'Group' column to define the arrays? (Y/n)
	```

	Earlier versions of actel used a 'Group' column to group arrays. This failsafe allows you to bypass the issues this would cause.

	```
	Error: The spatial file must contain an 'Array' column.
	Error: The spatial file must contain at least one 'Receiver' column.
	Error: The biometrics file must contain an 'Release.date' column.
	Error: The biometrics file must contain an 'Signal' column.
	```

	Actel could not find an essential column in your input files. Please doublecheck the spelling of the columns in the input files.

	```
	Error: Could not recognise the data in the 'Type' column is only one of 'Hydrophone' or 'Release'. Please doublecheck the spatial file.
	Error: Could not recognise the data in the 'Release.date' column as POSIX-compatible timestamps. Please doublecheck the biometrics file.
	Error: Could not recognise the data in the 'Signal' column as integers. Please doublecheck the biometrics file.
	Error: Some fish have no 'Signal' information. Please doublecheck the biometrics file.
	```

	Some of the input data failed the "type of data" tests. Have a look at the specific column in your input file, sometimes a lost letter or space can disrupt the nature of the data. If the problem persists, attempt manually loading the file to R and check the contents in R for any inconsistencies.

	```
	W: File 'filename' does not match to any of the supported hydrophone file formats!
	   If your file corresponds to a hydrophone log and actel did not recognize it, please contact the developer team: [email]
	W: One file was excluded from further analyses.
	W: # files were excluded from further analyses.
	```

	Not all files in your 'detections' folder were recognised as hydrophone logs. Make sure you did not edit the detection files manually before feeding them to Actel. If the problem persists, contact the developer team.

1. **Automatic handling of exceptions**

	```
	M: No 'Type' column found in the stations file. Assigning all rows as hydrophones.
	M: No Release site has been indicated in the biometrics file. Creating a 'Release.site' column to avoid function failure. Filling with 'unspecified'.
	W: Some fish contain no release site information. You may want to doublecheck the data.
	   Filling the blanks with 'unspecified'.
	M: No 'Group' column found in the biometrics file. Assigning all fish to group 'All'.
	W: Some fish contain no group information. You may want to doublecheck the data.
	   Filling the blanks with 'unspecified'.
	```

	Actel can fix some gaps automatically for you. However, you will always receive a message notifying you of what was done, so you can be sure that everything is fine. For example, it is unexpected that only part of the fish would have no group or no release site information. It is up to you to decide if something is wrong.

1. **Previously compiled actel detections found**

	```
	M: The detections have been processed on [Timestamp].
	   If the input detection files were not changed, it is safe to use these again.
	   Reuse processed detections? (Y/n)
	```
	In large datasets, processing the detections can take a considerable amount of time. When you run actel in a set of data, actel saves the processed detections in your 'detections' folder, so you can use them later on to save time. If you are running actel again on he same dataset, and you have not changed the detection files, you can reuse the processed detections. If you are not sure, tell actel to not use the processed detections, and the detection files will be loaded and processed again.

1. **Data being excluded before analysis**

	```
	M: Discarding detection data previous to [start.timestamp] per user command ([#] detections discarded).	
	M: Discarding detection data posterior to [end.timestamp] per user command ([#] detections discarded).
	```

	If you have set `start.timestamp` or `end.timestamp`, actel will let you know how many detections were discarded.

	```
	M: Excluding tag(s) [tag list] from the analysis per used command (detections removed: [n per tag], respectively).
	```

	If you have set tags to be excluded through the `exclude.tags` variable, actel will confirm this exclusion and let you know how many detections were discarded.

### Errors and messages during the data analysis:

#### Initial checks

1. **Something is off with the receivers**

	```
  W: Detections from receivers [serial numbers] are present in the data, but these receivers are not part of the study's stations. Doublecheck potential errors.
	```

	Somewhere in your detection files, there are detections for hydrophones that are not listed in the spatial file. If some of your target tags are detected in these receivers, this warning will escalate to the one below.

	```
  W: Fish [transmitter] was detected in one or more receivers that are not listed in the study area (receiver(s): [receivers serial])!
  Possible options:
     a) Stop and doublecheck the data (recommended)
     b) Temporary include the hydrophone(s) to the stations list
  Which option should be followed?(a/b) 
	```

	At least one of your target tags were detected in a hydrophone that is not listed in the spatial file. If you are truly unsure about the provenance of this unknown receiver, you can temporarily include it to the stations list, and then have a look at the movement events to find out when were your fish detected there. Note that this hydrophone will not be used to determine the fish's arrival/departure points from the various sections.

	```
  W: No detections were found for receiver(s) [receivers serial].
	```

	One or more of the hydrophone listed in the spatial file had 0 detections in the detection files (not even noise/stray detections). While this is not bad on its own (perhaps nothing passed through that hydrophone), it may also mean that there are some detection files missing from the 'detections' folder.

1. **Something is off with the transmitters**

	```
  M: No detections were found in the input data which matched the target signals.
  Error: Stopping analysis due to absence of valid detections.
	```

	None of the signals in the biometrics file match the signals present in the detection files. Could there be something wrong with the signals in the biometrics file? If you are sure that your fish were detected and actel keeps showing this message, contact the development team.

	```
  Error: One or more signals match more than one tag in the detections! Showing relevant signals/tags.
     Signal [Signal] was found on tags [tag1], [tag2], [...]
  Error: Fatal exception found. Stopping analysis.
	```

	To simplify the sorting and analysing process, actel works based on the tag signals alone. Usually, all the tags you are working with will be operating in the same code space, so this is not a problem. However, it is possible for a stray tag (i.e. a tag from an animal tagged by someone else) to come within range of your hydrophones while your study is going on. Should this stray tag have an identical signal to one of your target tags, then actel will not know which of the tag is yours.

	To fix this, find out which of the tags listed is yours, and include all the others with the same signal in the 'excluded.tags' variable.

#### Exceptions during Movement event creation

1. **Array mismatch**

	```
	Error: There is a mismatch between the expected first array of a release site and the list of arrays.
	Please correct this before continuing.
	```

	There could be a typo in the array listed as first array for a release site. Doublecheck the spatial file and make sure the arrays listed in the release sites match the arrays listed in the hydrophones.

1. **Backwards movements**
  
	```
  W: Fish [transmitter] was detected behind of its release site! Opening relevant data for inspection.
     Release site: [...]
     Expected first array: [...]
     Movement table for fish [transmitter]:
     [...]
     You may either:
       a) Stop the analysis if the expected first array is wrong;
       b) Continue as is (does not impact the results);
       c) Remove a movement event, if you are confident it is a false detection.
  Decision:(a/b/c/comment) 
	```

	A fish being released and moving in the opposite direction to what we expected is definitely not impossible. However, it is usually worth a close look. As such, when a fish is detected behind of its release site (i.e. upstream for a seaward migrating fish), actel will display a summary and let you decide what to do. If the movement seems real, you can always let the analysis run as it is.

#### Exceptions while filling in the timetable

1. **Unknown hydrophones**

	```
	M: Disregarding [#] unknown events from fish [transmitter]'s movement table.
	W: Fish [transmitter] only moved through unknown hydrophones. Considered invalid.
	```

	If you are running the analysis with unknown hydrophones (see the messages for these above), these will be excluded from the timetable analysis. If the fish only moved through unknown hydrophones, the message will escalate to a warning.

1. **Triggering override**
	
	```
	M: Override has been triggered for fish [transmitter]. Entering full manual mode.
	```

	If you included fish in the `override` variable, this message will show up when it is their turn to be analysed. You can find more details on (how to operate full manual mode here.](5.refining_results.html)


1. **Cautious assignment**

	```
	W: No [section] detection events with more than one detection were found for fish [transmitter]. Opening movements list for inspection.
	[...]
	Which event should be considered the LAST [section] detection event?
	```

	If `cautious.assignment` is set to TRUE, actel will avoid assigning movements with one detection as moments of entry/leaving a given section. However, if there are no movements with more than one detection, actel will ask you to intervene. This message does not show up if `cautious.assignment` is set to FALSE, because then all movement events are considered equally valid.

	```
	M: Fish [transmitter] only has one movement entry ([array]) with [#] detections. Considered invalid."
	```

	If a fish only has one movement event and the number of detections within that event is below the number set at `minimum.detections`, the detection(s) for this fish will be considered invalid and the fish will be considered lost at release.

1. **Backwards movements**

	```
	W: Inter-section backwards movements were detected for Fish [transmitter].
	Would you like to see the movement table for fish [transmitter]?(y/N) 
	W: Inter-section backwards movements were detected for Fish [transmitter] and the last events are not ordered!
	   Opening movements list for inspection.
	```

	A fish moving a bit up and down is not much to worry about. But if these backward movements involve moving from one section of your study area to another (i.e. a seaward fish moved to the sea and then back to the river), actel will issue a warning. You can then verify the movements and the assigned last events.

	If there are backwards inter-section movements and, on top of that, the last events are not ordered (i.e. the fish was not last seen on section A before being last seen on section B), then the warning will escalate and you will have to take action.

	You can [read more about backward movements here.](3.0.the_sorting_process.html#backwards-movements)

#### Exceptions while merging the timetable and the fish information

1. **Detections before release**

	```
	Error: Fish [transmitter] was detected before being released!
	  Release time:
	  First valid detection:
	  Movement table for fish [transmitter]:
	  [...]
	You may either:
	  a) Stop the analysis and check your data;
	  b) Continue anyway (time and speed from release to first valid detection will not be calculated).
	```

	Usually this can mean one of three things: The first and most obvious is that there is a mistake in the release time information. Secondly, either that tag may have been used as a tester before being implanted or one hydrophone may have been used to activate the tags before deployment. Lastly, the tag and the hydrophone may have been in close range in transport and the hydrophone has picked up some detections on the way.

	If you are sure that the release time information is correct, and the detections before release seem consistent with the second or third case presented above, you can use the `start.timestamp` variable to trim the detection data and remove the undesired detections. However, we recommend that you **always** exhaust other possibilities before doing this, to make sure there are no real mistakes in the data.

### Errors and messages while saving and terminating:

1. **Pre-existing files**

	```
	M: An actel results file is already present in the present directory, saving new results as 'actel_results.#.RData'.
	M: An actel report is already present in the present directory, saving new report as 'actel_report.#.pdf'.	
	```
	If there are already actel-generated files (reports and results) in the current directory, actel will save the new reports in a new file with a different name, to avoid overwriting previous results.

1. **Failing to compile report**

	```
	Something went wrong when compiling the PDF report. Please find the individual graphics in the folder 'Report'.
	If you do not have LaTeX installed, check out how to quickly get it running in the package vignettes.
	If you do have LaTeX installed, you can manually compile the file 'actel_report.tex', which has been stored in the folder 'Report'.
	```

	If you activated the `report` option, actel will attempt to compile a PDF report based on a TeX file. If you do not have TeX installed, you can [find out how to install TeX here](2.1.installing_tex.html). IF you have a TeX distribution installed and the problem persists, please contact the development team.

[Back to top.](#)