---
title: "2.1) From raw data to movements"
author: "Hugo Flávio"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{2.1) From raw data to movements}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Index

1. [Preparing your data](a-0_workspace_requirements.html)
    1. [Structuring the study area](a-1_study_area.html)
    1. [Creating a distances matrix](a-2_distances_matrix.html)
1. [explore()](b-0_explore.html)
    1. [__From raw to movements__](b-1_explore_processes.html)
    1. [Inspecting the explore() results](b-2_explore_results.html)
1. [migration()](c-0_migration.html)
    1. [Processes behind migration()](c-1_migration_processes.html)
    1. [Inspecting the migration() results](c-2_migration_results.html)
    1. [Manual mode in migration()](c-3_migration_manual_mode.html)
1. [residency()](d-0_residency.html)
    1. [Processes behind residency()](d-1_residency_processes.html)
    1. [Inspecting the residency() results](d-2_residency_results.html)
1. [Errors and messages](e-0_messages.html)


## Making sure everything checks out

The first thing actel does is import your data. This also includes all of your detection files, which can take a bit of time. Then, actel performs many verifications to make sure everything is all right. As the list of checks is long, I won't explore each one of them in detail here. Should something be out of the ordinary, actel will let you know with a warning or an error message, depending on the severity of the issue. 

If you need help with any messages, warnings or errors, you can find more about them in the [list of errors and messages](e-0_messages.html).

## Organising the detections

Once everything is in place, actel will start by:

1. Splitting the detections by transmitter,
2. Match the signals listed in the biometrics, 
3. Keep only the detections useful for the study. 

It is at this point that the argument [exclude.tags](b-0_explore.html#exclude.tags) comes in:

Actel uses the tag's signal to find your fish. However, if two tags with the same signal but different code spaces show up at your study area, actel will not know which one to choose. Should this happen, you must specify which tag **should be excluded** in the `exclude.tags` argument and restart the analysis. You can [find an example here.](b-0_explore.html#exclude.tags)

Once the detections are sorted and validated, actel is ready to start compiling movement events.

Note:
  : If your detections contain data from stray tags (i.e. tags that do not belong to your study), a summary of this will be stored in a "stray_tags.csv" file.

## From detections to movements

The process of compiling movement events is entirely automatic, and the outcome depends on two things:

Arrays
  : When a fish moves from one receiver array to another, a new movement event is created. These arrays are defined by you in the [spatial file](a-0_workspace_requirements.html#spatial-file), so it is worth it to spend some time thinking about how you want to arrange your receivers.

`maximum.time`
  : This argument controls the creation of multiple events for consecutive detections on the same receiver array. You can [find more information about this argument here](b-0_explore.html#maximum.time).

By the end of this process, you will have a list containing the movement events for each of the target tags that were detected during the study.

## Checking event continuity

Upon finishing the movement event creation, actel checks if the fish moved between arrays as expected (i.e. sequential movement events are on adjacent events), or if the fish has been jumping around. Should the movement events look odd, actel will issue warnings and prompt user intervention, depending on [the values set for `jump.warning` and `jump.error`.](b-0_explore.html#jump.warning-and-jump.error)

If the jump size is bigger than `jump.warning`, actel will issue a warning:

````
W: Fish R64K-1234 jumped through 2 arrays in events 1 -> 2 (A1 -> A4).
````

If the jump size is bigger than `jump.error`, actel will ask you if you want to render any movement event invalid

````
W: Fish R64K-1234 jumped through 3 arrays in events 1 -> 2 (A1 -> A5).
M: Opening movement table of fish R64K-2791 for inspection:
[...]
Would you like to render any movement event invalid?(y/N/comment)
````

Note:
  : Rendering a movement event invalid **does not make it disappear**. However, future analyses will know that the **event should not be considered** (hence the "Valid" column).


## Bonus: Time of first detection at each array

The last thing explore() does is find out the time of first detection at each array, for each fish. This information is then used to plot [circular graphics in the report](b-2_explore_results.html#times), and is also returned within R as an output of the function.


## The explore() analysis ends here

This movement events list is the main output of the explore() analysis. This, together with the html report generated, will give you an idea of what your data looks like. To advance into more detailed analyses, you can proceed either to the __[migration()](c-0_migration.html)__ analysis or to the __[residency()](d-0_residency.html)__ analysis. These will use the movement events created here to extract more complex metrics!

Alternatively, you can also have a more __[detailed look at the outputs of the explore().](b-2_explore_results.html)__

[Back to top.](#)

