tests.home <- getwd()
setwd(tempdir())
test_that("createWorkspace deploys necessary files", {
	createWorkspace("actel_workspace")
	expect_true(dir.exists("actel_workspace"))
	expect_true(file.exists("actel_workspace/spatial.csv"))
	expect_true(file.exists("actel_workspace/biometrics.csv"))
	expect_true(file.exists("actel_workspace/deployments.csv"))
	expect_true(file.exists("actel_workspace/spatial.csv"))
	expect_true(dir.exists("actel_workspace/detections"))
	createWorkspace("test_name")
	expect_true(dir.exists("test_name"))
	unlink("actel_workspace", recursive = TRUE)
	unlink("test_name", recursive = TRUE)
})
setwd(tests.home)
